"""add account category and transaction

Revision ID: 0200ac14b92a
Revises: 830fe76cd3a7
Create Date: 2026-08-25 17:43:40.072562
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '0200ac14b92a'
down_revision: str | None = '830fe76cd3a7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('household_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('opening_balance_cents', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('opening_date', sa.Date(), nullable=False),
    sa.Column('include_in_net_worth', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('position', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_account_household_id'), 'account', ['household_id'], unique=False)
    op.create_index('uq_account_household_name', 'account', ['household_id', sa.literal_column('lower(name)')], unique=True)
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('household_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.Column('icon', sa.String(length=40), nullable=False),
    sa.Column('position', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_category_household_id'), 'category', ['household_id'], unique=False)
    op.create_index('uq_category_household_kind_name', 'category', ['household_id', 'kind', sa.literal_column('lower(name)')], unique=True)
    op.create_table('transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('household_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('amount_cents', sa.BigInteger(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('counter_account_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_adjustment', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(kind = 'transfer') = (counter_account_id IS NOT NULL)", name='ck_transaction_transfer_has_counter_account'),
    sa.CheckConstraint("NOT is_adjustment OR (category_id IS NULL AND kind <> 'transfer')", name='ck_transaction_adjustment_shape'),
    sa.CheckConstraint("kind <> 'transfer' OR category_id IS NULL", name='ck_transaction_transfer_has_no_category'),
    sa.CheckConstraint('amount_cents > 0', name='ck_transaction_amount_positive'),
    sa.CheckConstraint('counter_account_id IS NULL OR counter_account_id <> account_id', name='ck_transaction_counter_account_differs'),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['counter_account_id'], ['account.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['app_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_transaction_household_account', 'transaction', ['household_id', 'account_id'], unique=False)
    op.create_index('ix_transaction_household_category', 'transaction', ['household_id', 'category_id'], unique=False)
    op.create_index('ix_transaction_household_counter_account', 'transaction', ['household_id', 'counter_account_id'], unique=False)
    op.create_index('ix_transaction_household_date_id', 'transaction', ['household_id', 'date', 'id'], unique=False)
    op.create_index(op.f('ix_transaction_household_id'), 'transaction', ['household_id'], unique=False)
    # ### end Alembic commands ###

    # A starting set of categories, so the first sign-in has something to work
    # with instead of fourteen empty forms standing between you and recording a
    # spend. They are a proposal: rename them, archive them, add your own.
    #
    # Colours cycle through the six chart series and the icons come from the
    # curated list in domain/vocabulary.py — both are token names, not values.
    expenses = [
        ("Spesa", "ShoppingCart"),
        ("Casa", "House"),
        ("Trasporti", "Car"),
        ("Ristoranti", "UtensilsCrossed"),
        ("Salute", "HeartPulse"),
        ("Svago", "Film"),
        ("Abbonamenti", "Repeat"),
        ("Vestiti", "Shirt"),
        ("Regali", "Gift"),
        ("Altro", "Ellipsis"),
    ]
    incomes = [
        ("Stipendio", "Banknote"),
        ("Rimborso", "Repeat"),
        ("Regalo", "Gift"),
        ("Altro", "Ellipsis"),
    ]
    colors = ["chart-1", "chart-2", "chart-3", "chart-4", "chart-5", "chart-6"]

    rows = []
    for group, kind in ((expenses, "expense"), (incomes, "income")):
        for position, (name, icon) in enumerate(group, start=1):
            color = colors[(position - 1) % len(colors)]
            rows.append(
                "('{name}', '{kind}', '{color}', '{icon}', {position})".format(
                    name=name, kind=kind, color=color, icon=icon, position=position
                )
            )

    # Cross join against the single household row: the values carry no id, and
    # the seed follows whatever id that row happens to have.
    op.execute(
        "insert into category "
        "(household_id, name, kind, color, icon, position, is_archived) "
        "select h.id, v.name, v.kind, v.color, v.icon, v.position, false "
        "from (values " + ", ".join(rows) + ") "
        "as v(name, kind, color, icon, position), "
        "(select id from household order by id limit 1) as h"
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transaction_household_id'), table_name='transaction')
    op.drop_index('ix_transaction_household_date_id', table_name='transaction')
    op.drop_index('ix_transaction_household_counter_account', table_name='transaction')
    op.drop_index('ix_transaction_household_category', table_name='transaction')
    op.drop_index('ix_transaction_household_account', table_name='transaction')
    op.drop_table('transaction')
    op.drop_index('uq_category_household_kind_name', table_name='category')
    op.drop_index(op.f('ix_category_household_id'), table_name='category')
    op.drop_table('category')
    op.drop_index('uq_account_household_name', table_name='account')
    op.drop_index(op.f('ix_account_household_id'), table_name='account')
    op.drop_table('account')
    # ### end Alembic commands ###
